// Theme definitions for Jammify
// Each theme contains CSS variable values for customization

export const themes = {
    default: {
        name: "Default",
        colors: {
            background: "#121212",
            foreground: "#e2e8f0",
            card: "#171717",
            "card-foreground": "#e2e8f0",
            popover: "#242424",
            "popover-foreground": "#a9a9a9",
            primary: "#006239",
            "primary-foreground": "#dde8e3",
            secondary: "#242424",
            "secondary-foreground": "#fafafa",
            muted: "#1f1f1f",
            "muted-foreground": "#a2a2a2",
            accent: "#313131",
            "accent-foreground": "#fafafa",
            destructive: "#541c15",
            "destructive-foreground": "#ede9e8",
            border: "#292929",
            input: "#242424",
            ring: "#4ade80",
        },
        preview: ["#121212", "#006239", "#4ade80", "#292929"],
    },

    neutralLight: {
        name: "Neutral Light",
        colors: {
            background: "#ffffff",
            foreground: "#0a0a0a",
            card: "#ffffff",
            "card-foreground": "#0a0a0a",
            popover: "#ffffff",
            "popover-foreground": "#0a0a0a",
            primary: "#171717",
            "primary-foreground": "#fafafa",
            secondary: "#f5f5f5",
            "secondary-foreground": "#171717",
            muted: "#f5f5f5",
            "muted-foreground": "#737373",
            accent: "#f5f5f5",
            "accent-foreground": "#171717",
            destructive: "#e7000b",
            "destructive-foreground": "#ffffff",
            border: "#e5e5e5",
            input: "#e5e5e5",
            ring: "#a1a1a1",
        },
        preview: ["#ffffff", "#171717", "#a1a1a1", "#e5e5e5"],
    },

    neutralDark: {
        name: "Neutral Dark",
        colors: {
            background: "#0a0a0a",
            foreground: "#fafafa",
            card: "#171717",
            "card-foreground": "#fafafa",
            popover: "#262626",
            "popover-foreground": "#fafafa",
            primary: "#e5e5e5",
            "primary-foreground": "#171717",
            secondary: "#262626",
            "secondary-foreground": "#fafafa",
            muted: "#262626",
            "muted-foreground": "#a1a1a1",
            accent: "#404040",
            "accent-foreground": "#fafafa",
            destructive: "#ff6467",
            "destructive-foreground": "#fafafa",
            border: "#282828",
            input: "#343434",
            ring: "#737373",
        },
        preview: ["#0a0a0a", "#e5e5e5", "#737373", "#282828"],
    },

    amberLight: {
        name: "Amber Light",
        colors: {
            background: "#ffffff",
            foreground: "#262626",
            card: "#ffffff",
            "card-foreground": "#262626",
            popover: "#ffffff",
            "popover-foreground": "#262626",
            primary: "#f59e0b",
            "primary-foreground": "#000000",
            secondary: "#f3f4f6",
            "secondary-foreground": "#4b5563",
            muted: "#f9fafb",
            "muted-foreground": "#6b7280",
            accent: "#fffbeb",
            "accent-foreground": "#92400e",
            destructive: "#ef4444",
            "destructive-foreground": "#ffffff",
            border: "#e5e7eb",
            input: "#e5e7eb",
            ring: "#f59e0b",
        },
        preview: ["#ffffff", "#f59e0b", "#fffbeb", "#e5e7eb"],
    },

    amberDark: {
        name: "Amber Dark",
        colors: {
            background: "#171717",
            foreground: "#e5e5e5",
            card: "#262626",
            "card-foreground": "#e5e5e5",
            popover: "#262626",
            "popover-foreground": "#e5e5e5",
            primary: "#f59e0b",
            "primary-foreground": "#000000",
            secondary: "#262626",
            "secondary-foreground": "#e5e5e5",
            muted: "#1f1f1f",
            "muted-foreground": "#a3a3a3",
            accent: "#92400e",
            "accent-foreground": "#fde68a",
            destructive: "#ef4444",
            "destructive-foreground": "#ffffff",
            border: "#404040",
            input: "#404040",
            ring: "#f59e0b",
        },
        preview: ["#171717", "#f59e0b", "#92400e", "#404040"],
    },

    amethystHazeLight: {
        name: "Amethyst Haze Light",
        colors: {
            background: "#f8f7fa",
            foreground: "#3d3c4f",
            card: "#ffffff",
            "card-foreground": "#3d3c4f",
            popover: "#ffffff",
            "popover-foreground": "#3d3c4f",
            primary: "#8a79ab",
            "primary-foreground": "#f8f7fa",
            secondary: "#dfd9ec",
            "secondary-foreground": "#3d3c4f",
            muted: "#dcd9e3",
            "muted-foreground": "#6b6880",
            accent: "#e6a5b8",
            "accent-foreground": "#4b2e36",
            destructive: "#d95c5c",
            "destructive-foreground": "#f8f7fa",
            border: "#cec9d9",
            input: "#eae7f0",
            ring: "#8a79ab",
        },
        preview: ["#f8f7fa", "#8a79ab", "#e6a5b8", "#cec9d9"],
    },

    amethystHazeDark: {
        name: "Amethyst Haze Dark",
        colors: {
            background: "#1a1823",
            foreground: "#e0ddef",
            card: "#232030",
            "card-foreground": "#e0ddef",
            popover: "#232030",
            "popover-foreground": "#e0ddef",
            primary: "#a995c9",
            "primary-foreground": "#1a1823",
            secondary: "#5a5370",
            "secondary-foreground": "#e0ddef",
            muted: "#242031",
            "muted-foreground": "#a09aad",
            accent: "#372e3f",
            "accent-foreground": "#f2b8c6",
            destructive: "#e57373",
            "destructive-foreground": "#1a1823",
            border: "#302c40",
            input: "#2a273a",
            ring: "#a995c9",
        },
        preview: ["#1a1823", "#a995c9", "#f2b8c6", "#302c40"],
    },

    boldTechLight: {
        name: "Bold Tech Light",
        colors: {
            background: "#ffffff",
            foreground: "#312e81",
            card: "#ffffff",
            "card-foreground": "#312e81",
            popover: "#ffffff",
            "popover-foreground": "#312e81",
            primary: "#8b5cf6",
            "primary-foreground": "#ffffff",
            secondary: "#f3f0ff",
            "secondary-foreground": "#4338ca",
            muted: "#f5f3ff",
            "muted-foreground": "#7c3aed",
            accent: "#dbeafe",
            "accent-foreground": "#1e40af",
            destructive: "#ef4444",
            "destructive-foreground": "#ffffff",
            border: "#e0e7ff",
            input: "#e0e7ff",
            ring: "#8b5cf6",
        },
        preview: ["#ffffff", "#8b5cf6", "#dbeafe", "#e0e7ff"],
    },

    boldTechDark: {
        name: "Bold Tech Dark",
        colors: {
            background: "#0f172a",
            foreground: "#e0e7ff",
            card: "#1e1b4b",
            "card-foreground": "#e0e7ff",
            popover: "#1e1b4b",
            "popover-foreground": "#e0e7ff",
            primary: "#8b5cf6",
            "primary-foreground": "#ffffff",
            secondary: "#1e1b4b",
            "secondary-foreground": "#e0e7ff",
            muted: "#171447",
            "muted-foreground": "#c4b5fd",
            accent: "#4338ca",
            "accent-foreground": "#e0e7ff",
            destructive: "#ef4444",
            "destructive-foreground": "#ffffff",
            border: "#2e1065",
            input: "#2e1065",
            ring: "#8b5cf6",
        },
        preview: ["#0f172a", "#8b5cf6", "#4338ca", "#2e1065"],
    },

    bubblegumLight: {
        name: "Bubblegum Light",
        colors: {
            background: "#f6e6ee",
            foreground: "#5b5b5b",
            card: "#fdedc9",
            "card-foreground": "#5b5b5b",
            popover: "#ffffff",
            "popover-foreground": "#5b5b5b",
            primary: "#d04f99",
            "primary-foreground": "#ffffff",
            secondary: "#8acfd1",
            "secondary-foreground": "#333333",
            muted: "#b2e1eb",
            "muted-foreground": "#7a7a7a",
            accent: "#fbe2a7",
            "accent-foreground": "#333333",
            destructive: "#f96f70",
            "destructive-foreground": "#ffffff",
            border: "#d04f99",
            input: "#e4e4e4",
            ring: "#e670ab",
        },
        preview: ["#f6e6ee", "#d04f99", "#8acfd1", "#fbe2a7"],
    },

    bubblegumDark: {
        name: "Bubblegum Dark",
        colors: {
            background: "#12242e",
            foreground: "#f3e3ea",
            card: "#1c2e38",
            "card-foreground": "#f3e3ea",
            popover: "#1c2e38",
            "popover-foreground": "#f3e3ea",
            primary: "#fbe2a7",
            "primary-foreground": "#12242e",
            secondary: "#e4a2b1",
            "secondary-foreground": "#12242e",
            muted: "#24272b",
            "muted-foreground": "#e4a2b1",
            accent: "#c67b96",
            "accent-foreground": "#f3e3ea",
            destructive: "#e35ea4",
            "destructive-foreground": "#12242e",
            border: "#324859",
            input: "#20333d",
            ring: "#50afb6",
        },
        preview: ["#12242e", "#fbe2a7", "#e4a2b1", "#50afb6"],
    },

    caffeineLight: {
        name: "Caffeine Light",
        colors: {
            background: "#f9f9f9",
            foreground: "#202020",
            card: "#fcfcfc",
            "card-foreground": "#202020",
            popover: "#fcfcfc",
            "popover-foreground": "#202020",
            primary: "#644a40",
            "primary-foreground": "#ffffff",
            secondary: "#ffdfb5",
            "secondary-foreground": "#582d1d",
            muted: "#efefef",
            "muted-foreground": "#646464",
            accent: "#e8e8e8",
            "accent-foreground": "#202020",
            destructive: "#e54d2e",
            "destructive-foreground": "#ffffff",
            border: "#d8d8d8",
            input: "#d8d8d8",
            ring: "#644a40",
        },
        preview: ["#f9f9f9", "#644a40", "#ffdfb5", "#d8d8d8"],
    },

    caffeineDark: {
        name: "Caffeine Dark",
        colors: {
            background: "#111111",
            foreground: "#eeeeee",
            card: "#191919",
            "card-foreground": "#eeeeee",
            popover: "#191919",
            "popover-foreground": "#eeeeee",
            primary: "#ffe0c2",
            "primary-foreground": "#081a1b",
            secondary: "#393028",
            "secondary-foreground": "#ffe0c2",
            muted: "#222222",
            "muted-foreground": "#b4b4b4",
            accent: "#2a2a2a",
            "accent-foreground": "#eeeeee",
            destructive: "#e54d2e",
            "destructive-foreground": "#ffffff",
            border: "#201e18",
            input: "#484848",
            ring: "#ffe0c2",
        },
        preview: ["#111111", "#ffe0c2", "#393028", "#201e18"],
    },

    catppuccinLight: {
        name: "Catppuccin Light",
        colors: {
            background: "#eff1f5",
            foreground: "#4c4f69",
            card: "#ffffff",
            "card-foreground": "#4c4f69",
            popover: "#ccd0da",
            "popover-foreground": "#4c4f69",
            primary: "#8839ef",
            "primary-foreground": "#ffffff",
            secondary: "#ccd0da",
            "secondary-foreground": "#4c4f69",
            muted: "#dce0e8",
            "muted-foreground": "#6c6f85",
            accent: "#04a5e5",
            "accent-foreground": "#ffffff",
            destructive: "#d20f39",
            "destructive-foreground": "#ffffff",
            border: "#bcc0cc",
            input: "#ccd0da",
            ring: "#8839ef",
        },
        preview: ["#eff1f5", "#8839ef", "#04a5e5", "#bcc0cc"],
    },

    catppuccinDark: {
        name: "Catppuccin Dark",
        colors: {
            background: "#181825",
            foreground: "#cdd6f4",
            card: "#1e1e2e",
            "card-foreground": "#cdd6f4",
            popover: "#45475a",
            "popover-foreground": "#cdd6f4",
            primary: "#cba6f7",
            "primary-foreground": "#1e1e2e",
            secondary: "#585b70",
            "secondary-foreground": "#cdd6f4",
            muted: "#292c3c",
            "muted-foreground": "#a6adc8",
            accent: "#89dceb",
            "accent-foreground": "#1e1e2e",
            destructive: "#f38ba8",
            "destructive-foreground": "#1e1e2e",
            border: "#313244",
            input: "#313244",
            ring: "#cba6f7",
        },
        preview: ["#181825", "#cba6f7", "#89dceb", "#313244"],
    },

    claudeLight: {
        name: "Claude Light",
        colors: {
            background: "#faf9f5",
            foreground: "#3d3929",
            card: "#faf9f5",
            "card-foreground": "#141413",
            popover: "#ffffff",
            "popover-foreground": "#28261b",
            primary: "#c96442",
            "primary-foreground": "#ffffff",
            secondary: "#e9e6dc",
            "secondary-foreground": "#535146",
            muted: "#ede9de",
            "muted-foreground": "#83827d",
            accent: "#e9e6dc",
            "accent-foreground": "#28261b",
            destructive: "#141413",
            "destructive-foreground": "#ffffff",
            border: "#dad9d4",
            input: "#b4b2a7",
            ring: "#c96442",
        },
        preview: ["#faf9f5", "#c96442", "#e9e6dc", "#dad9d4"],
    },

    claudeDark: {
        name: "Claude Dark",
        colors: {
            background: "#262624",
            foreground: "#c3c0b6",
            card: "#262624",
            "card-foreground": "#faf9f5",
            popover: "#30302e",
            "popover-foreground": "#e5e5e2",
            primary: "#d97757",
            "primary-foreground": "#ffffff",
            secondary: "#faf9f5",
            "secondary-foreground": "#30302e",
            muted: "#1b1b19",
            "muted-foreground": "#b7b5a9",
            accent: "#1a1915",
            "accent-foreground": "#f5f4ee",
            destructive: "#ef4444",
            "destructive-foreground": "#ffffff",
            border: "#3e3e38",
            input: "#52514a",
            ring: "#d97757",
        },
        preview: ["#262624", "#d97757", "#1a1915", "#3e3e38"],
    },

    claymorphismLight: {
        name: "Claymorphism Light",
        colors: {
            background: "#e7e5e4",
            foreground: "#1e293b",
            card: "#f5f5f4",
            "card-foreground": "#1e293b",
            popover: "#f5f5f4",
            "popover-foreground": "#1e293b",
            primary: "#6366f1",
            "primary-foreground": "#ffffff",
            secondary: "#d6d3d1",
            "secondary-foreground": "#4b5563",
            muted: "#e7e5e4",
            "muted-foreground": "#6b7280",
            accent: "#f3e5f5",
            "accent-foreground": "#374151",
            destructive: "#ef4444",
            "destructive-foreground": "#ffffff",
            border: "#d6d3d1",
            input: "#d6d3d1",
            ring: "#6366f1",
        },
        preview: ["#e7e5e4", "#6366f1", "#f3e5f5", "#d6d3d1"],
    },

    claymorphismDark: {
        name: "Claymorphism Dark",
        colors: {
            background: "#1e1b18",
            foreground: "#e2e8f0",
            card: "#2c2825",
            "card-foreground": "#e2e8f0",
            popover: "#2c2825",
            "popover-foreground": "#e2e8f0",
            primary: "#818cf8",
            "primary-foreground": "#1e1b18",
            secondary: "#3a3633",
            "secondary-foreground": "#d1d5db",
            muted: "#1f1c19",
            "muted-foreground": "#9ca3af",
            accent: "#484441",
            "accent-foreground": "#d1d5db",
            destructive: "#ef4444",
            "destructive-foreground": "#1e1b18",
            border: "#3a3633",
            input: "#3a3633",
            ring: "#818cf8",
        },
        preview: ["#1e1b18", "#818cf8", "#484441", "#3a3633"],
    },

    cleanSlateLight: {
        name: "Clean Slate Light",
        colors: {
            background: "#f8fafc",
            foreground: "#1e293b",
            card: "#ffffff",
            "card-foreground": "#1e293b",
            popover: "#ffffff",
            "popover-foreground": "#1e293b",
            primary: "#6366f1",
            "primary-foreground": "#ffffff",
            secondary: "#e5e7eb",
            "secondary-foreground": "#374151",
            muted: "#f3f4f6",
            "muted-foreground": "#6b7280",
            accent: "#e0e7ff",
            "accent-foreground": "#374151",
            destructive: "#ef4444",
            "destructive-foreground": "#ffffff",
            border: "#d1d5db",
            input: "#d1d5db",
            ring: "#6366f1",
        },
        preview: ["#f8fafc", "#6366f1", "#e0e7ff", "#d1d5db"],
    },

    cleanSlateDark: {
        name: "Clean Slate Dark",
        colors: {
            background: "#0f172a",
            foreground: "#e2e8f0",
            card: "#1e293b",
            "card-foreground": "#e2e8f0",
            popover: "#1e293b",
            "popover-foreground": "#e2e8f0",
            primary: "#818cf8",
            "primary-foreground": "#0f172a",
            secondary: "#2d3748",
            "secondary-foreground": "#d1d5db",
            muted: "#152032",
            "muted-foreground": "#9ca3af",
            accent: "#374151",
            "accent-foreground": "#d1d5db",
            destructive: "#ef4444",
            "destructive-foreground": "#0f172a",
            border: "#4b5563",
            input: "#4b5563",
            ring: "#818cf8",
        },
        preview: ["#0f172a", "#818cf8", "#374151", "#4b5563"],
    },

    cosmicNightLight: {
        name: "Cosmic Night Light",
        colors: {
            background: "#f5f5ff",
            foreground: "#2a2a4a",
            card: "#ffffff",
            "card-foreground": "#2a2a4a",
            popover: "#ffffff",
            "popover-foreground": "#2a2a4a",
            primary: "#6e56cf",
            "primary-foreground": "#ffffff",
            secondary: "#e4dfff",
            "secondary-foreground": "#4a4080",
            muted: "#f0f0fa",
            "muted-foreground": "#6c6c8a",
            accent: "#d8e6ff",
            "accent-foreground": "#2a2a4a",
            destructive: "#ff5470",
            "destructive-foreground": "#ffffff",
            border: "#e0e0f0",
            input: "#e0e0f0",
            ring: "#6e56cf",
        },
        preview: ["#f5f5ff", "#6e56cf", "#d8e6ff", "#e0e0f0"],
    },

    cosmicNightDark: {
        name: "Cosmic Night Dark",
        colors: {
            background: "#0f0f1a",
            foreground: "#e2e2f5",
            card: "#1a1a2e",
            "card-foreground": "#e2e2f5",
            popover: "#1a1a2e",
            "popover-foreground": "#e2e2f5",
            primary: "#a48fff",
            "primary-foreground": "#0f0f1a",
            secondary: "#2d2b55",
            "secondary-foreground": "#c4c2ff",
            muted: "#222244",
            "muted-foreground": "#a0a0c0",
            accent: "#303060",
            "accent-foreground": "#e2e2f5",
            destructive: "#ff5470",
            "destructive-foreground": "#ffffff",
            border: "#303052",
            input: "#303052",
            ring: "#a48fff",
        },
        preview: ["#0f0f1a", "#a48fff", "#303060", "#303052"],
    },

    cyberpunkLight: {
        name: "Cyberpunk Light",
        colors: {
            background: "#f8f9fa",
            foreground: "#0c0c1d",
            card: "#ffffff",
            "card-foreground": "#0c0c1d",
            popover: "#ffffff",
            "popover-foreground": "#0c0c1d",
            primary: "#ff00c8",
            "primary-foreground": "#ffffff",
            secondary: "#f0f0ff",
            "secondary-foreground": "#0c0c1d",
            muted: "#f0f0ff",
            "muted-foreground": "#0c0c1d",
            accent: "#00ffcc",
            "accent-foreground": "#0c0c1d",
            destructive: "#ff3d00",
            "destructive-foreground": "#ffffff",
            border: "#dfe6e9",
            input: "#dfe6e9",
            ring: "#ff00c8",
        },
        preview: ["#f8f9fa", "#ff00c8", "#00ffcc", "#dfe6e9"],
    },

    cyberpunkDark: {
        name: "Cyberpunk Dark",
        colors: {
            background: "#0c0c1d",
            foreground: "#eceff4",
            card: "#1e1e3f",
            "card-foreground": "#eceff4",
            popover: "#1e1e3f",
            "popover-foreground": "#eceff4",
            primary: "#ff00c8",
            "primary-foreground": "#ffffff",
            secondary: "#1e1e3f",
            "secondary-foreground": "#eceff4",
            muted: "#151530",
            "muted-foreground": "#8085a6",
            accent: "#00ffcc",
            "accent-foreground": "#0c0c1d",
            destructive: "#ff3d00",
            "destructive-foreground": "#ffffff",
            border: "#2e2e5e",
            input: "#2e2e5e",
            ring: "#ff00c8",
        },
        preview: ["#0c0c1d", "#ff00c8", "#00ffcc", "#2e2e5e"],
    },

    darkmatterLight: {
        name: "Darkmatter Light",
        colors: {
            background: "#ffffff",
            foreground: "#111827",
            card: "#ffffff",
            "card-foreground": "#111827",
            popover: "#ffffff",
            "popover-foreground": "#111827",
            primary: "#d87943",
            "primary-foreground": "#ffffff",
            secondary: "#527575",
            "secondary-foreground": "#ffffff",
            muted: "#f3f4f6",
            "muted-foreground": "#6b7280",
            accent: "#eeeeee",
            "accent-foreground": "#111827",
            destructive: "#ef4444",
            "destructive-foreground": "#fafafa",
            border: "#e5e7eb",
            input: "#e5e7eb",
            ring: "#d87943",
        },
        preview: ["#ffffff", "#d87943", "#527575", "#e5e7eb"],
    },

    darkmatterDark: {
        name: "Darkmatter Dark",
        colors: {
            background: "#121113",
            foreground: "#c1c1c1",
            card: "#121212",
            "card-foreground": "#c1c1c1",
            popover: "#121113",
            "popover-foreground": "#c1c1c1",
            primary: "#e78a53",
            "primary-foreground": "#121113",
            secondary: "#5f8787",
            "secondary-foreground": "#121113",
            muted: "#222222",
            "muted-foreground": "#888888",
            accent: "#333333",
            "accent-foreground": "#c1c1c1",
            destructive: "#5f8787",
            "destructive-foreground": "#121113",
            border: "#222222",
            input: "#222222",
            ring: "#e78a53",
        },
        preview: ["#121113", "#e78a53", "#5f8787", "#222222"],
    },

    doom64Light: {
        name: "Doom 64 Light",
        colors: {
            background: "#cccccc",
            foreground: "#1f1f1f",
            card: "#b0b0b0",
            "card-foreground": "#1f1f1f",
            popover: "#b0b0b0",
            "popover-foreground": "#1f1f1f",
            primary: "#b71c1c",
            "primary-foreground": "#ffffff",
            secondary: "#556b2f",
            "secondary-foreground": "#ffffff",
            muted: "#b8b8b8",
            "muted-foreground": "#4a4a4a",
            accent: "#4682b4",
            "accent-foreground": "#ffffff",
            destructive: "#ff6f00",
            "destructive-foreground": "#000000",
            border: "#505050",
            input: "#505050",
            ring: "#b71c1c",
        },
        preview: ["#cccccc", "#b71c1c", "#556b2f", "#4682b4"],
    },

    doom64Dark: {
        name: "Doom 64 Dark",
        colors: {
            background: "#1a1a1a",
            foreground: "#e0e0e0",
            card: "#2a2a2a",
            "card-foreground": "#e0e0e0",
            popover: "#2a2a2a",
            "popover-foreground": "#e0e0e0",
            primary: "#e53935",
            "primary-foreground": "#ffffff",
            secondary: "#689f38",
            "secondary-foreground": "#000000",
            muted: "#252525",
            "muted-foreground": "#a0a0a0",
            accent: "#64b5f6",
            "accent-foreground": "#000000",
            destructive: "#ffa000",
            "destructive-foreground": "#000000",
            border: "#4a4a4a",
            input: "#4a4a4a",
            ring: "#e53935",
        },
        preview: ["#1a1a1a", "#e53935", "#689f38", "#64b5f6"],
    },

    elegantLuxuryLight: {
        name: "Elegant Luxury Light",
        colors: {
            background: "#faf7f5",
            foreground: "#1a1a1a",
            card: "#faf7f5",
            "card-foreground": "#1a1a1a",
            popover: "#faf7f5",
            "popover-foreground": "#1a1a1a",
            primary: "#9b2c2c",
            "primary-foreground": "#ffffff",
            secondary: "#fdf2d6",
            "secondary-foreground": "#805500",
            muted: "#f0ebe8",
            "muted-foreground": "#57534e",
            accent: "#fef3c7",
            "accent-foreground": "#7f1d1d",
            destructive: "#991b1b",
            "destructive-foreground": "#ffffff",
            border: "#f5e8d2",
            input: "#f5e8d2",
            ring: "#9b2c2c",
        },
        preview: ["#faf7f5", "#9b2c2c", "#fef3c7", "#f5e8d2"],
    },

    elegantLuxuryDark: {
        name: "Elegant Luxury Dark",
        colors: {
            background: "#1c1917",
            foreground: "#f5f5f4",
            card: "#292524",
            "card-foreground": "#f5f5f4",
            popover: "#292524",
            "popover-foreground": "#f5f5f4",
            primary: "#b91c1c",
            "primary-foreground": "#faf7f5",
            secondary: "#92400e",
            "secondary-foreground": "#fef3c7",
            muted: "#1f1c1a",
            "muted-foreground": "#d6d3d1",
            accent: "#b45309",
            "accent-foreground": "#fef3c7",
            destructive: "#ef4444",
            "destructive-foreground": "#ffffff",
            border: "#44403c",
            input: "#44403c",
            ring: "#b91c1c",
        },
        preview: ["#1c1917", "#b91c1c", "#b45309", "#44403c"],
    },

    graphiteLight: {
        name: "Graphite Light",
        colors: {
            background: "#f0f0f0",
            foreground: "#333333",
            card: "#f5f5f5",
            "card-foreground": "#333333",
            popover: "#f5f5f5",
            "popover-foreground": "#333333",
            primary: "#606060",
            "primary-foreground": "#ffffff",
            secondary: "#e0e0e0",
            "secondary-foreground": "#333333",
            muted: "#d9d9d9",
            "muted-foreground": "#666666",
            accent: "#c0c0c0",
            "accent-foreground": "#333333",
            destructive: "#cc3333",
            "destructive-foreground": "#ffffff",
            border: "#d0d0d0",
            input: "#e0e0e0",
            ring: "#606060",
        },
        preview: ["#f0f0f0", "#606060", "#c0c0c0", "#d0d0d0"],
    },

    graphiteDark: {
        name: "Graphite Dark",
        colors: {
            background: "#1a1a1a",
            foreground: "#d9d9d9",
            card: "#202020",
            "card-foreground": "#d9d9d9",
            popover: "#202020",
            "popover-foreground": "#d9d9d9",
            primary: "#a0a0a0",
            "primary-foreground": "#1a1a1a",
            secondary: "#303030",
            "secondary-foreground": "#d9d9d9",
            muted: "#2a2a2a",
            "muted-foreground": "#808080",
            accent: "#404040",
            "accent-foreground": "#d9d9d9",
            destructive: "#e06666",
            "destructive-foreground": "#ffffff",
            border: "#353535",
            input: "#303030",
            ring: "#a0a0a0",
        },
        preview: ["#1a1a1a", "#a0a0a0", "#404040", "#353535"],
    },

    kodamaGroveLight: {
        name: "Kodama Grove Light",
        colors: {
            background: "#e4d7b0",
            foreground: "#5c4b3e",
            card: "#e7dbbf",
            "card-foreground": "#5c4b3e",
            popover: "#f3ead2",
            "popover-foreground": "#5c4b3e",
            primary: "#8d9d4f",
            "primary-foreground": "#fdfbf6",
            secondary: "#decea0",
            "secondary-foreground": "#5c4b3e",
            muted: "#decea0",
            "muted-foreground": "#85766a",
            accent: "#dbc894",
            "accent-foreground": "#5c4b3e",
            destructive: "#d98b7e",
            "destructive-foreground": "#faf8f2",
            border: "#b19681",
            input: "#dbc894",
            ring: "#9db18c",
        },
        preview: ["#e4d7b0", "#8d9d4f", "#dbc894", "#b19681"],
    },

    kodamaGroveDark: {
        name: "Kodama Grove Dark",
        colors: {
            background: "#3a3529",
            foreground: "#ede4d4",
            card: "#413c33",
            "card-foreground": "#ede4d4",
            popover: "#413c33",
            "popover-foreground": "#ede4d4",
            primary: "#8a9f7b",
            "primary-foreground": "#2a2521",
            secondary: "#5a5345",
            "secondary-foreground": "#ede4d4",
            muted: "#4a4439",
            "muted-foreground": "#a8a096",
            accent: "#a18f5c",
            "accent-foreground": "#2a2521",
            destructive: "#b5766a",
            "destructive-foreground": "#f0e9db",
            border: "#5a5345",
            input: "#5a5345",
            ring: "#8a9f7b",
        },
        preview: ["#3a3529", "#8a9f7b", "#a18f5c", "#5a5345"],
    },

    midnightBloomLight: {
        name: "Midnight Bloom Light",
        colors: {
            background: "#f9f9f9",
            foreground: "#333333",
            card: "#ffffff",
            "card-foreground": "#333333",
            popover: "#ffffff",
            "popover-foreground": "#333333",
            primary: "#6c5ce7",
            "primary-foreground": "#ffffff",
            secondary: "#a1c9f2",
            "secondary-foreground": "#333333",
            muted: "#c9c4b5",
            "muted-foreground": "#6e6e6e",
            accent: "#8b9467",
            "accent-foreground": "#ffffff",
            destructive: "#ef4444",
            "destructive-foreground": "#ffffff",
            border: "#d4d4d4",
            input: "#d4d4d4",
            ring: "#6c5ce7",
        },
        preview: ["#f9f9f9", "#6c5ce7", "#a1c9f2", "#8b9467"],
    },

    midnightBloomDark: {
        name: "Midnight Bloom Dark",
        colors: {
            background: "#1a1d23",
            foreground: "#e5e5e5",
            card: "#2f3436",
            "card-foreground": "#e5e5e5",
            popover: "#2f3436",
            "popover-foreground": "#e5e5e5",
            primary: "#6c5ce7",
            "primary-foreground": "#ffffff",
            secondary: "#4b0082",
            "secondary-foreground": "#e5e5e5",
            muted: "#444444",
            "muted-foreground": "#a3a3a3",
            accent: "#6495ed",
            "accent-foreground": "#e5e5e5",
            destructive: "#ef4444",
            "destructive-foreground": "#ffffff",
            border: "#444444",
            input: "#444444",
            ring: "#6c5ce7",
        },
        preview: ["#1a1d23", "#6c5ce7", "#4b0082", "#6495ed"],
    },

    mochaMousseLight: {
        name: "Mocha Mousse Light",
        colors: {
            background: "#f1f0e5",
            foreground: "#56453f",
            card: "#f1f0e5",
            "card-foreground": "#56453f",
            popover: "#ffffff",
            "popover-foreground": "#56453f",
            primary: "#a37764",
            "primary-foreground": "#ffffff",
            secondary: "#baab92",
            "secondary-foreground": "#ffffff",
            muted: "#e4c7b8",
            "muted-foreground": "#8a655a",
            accent: "#e4c7b8",
            "accent-foreground": "#56453f",
            destructive: "#1f1a17",
            "destructive-foreground": "#ffffff",
            border: "#baab92",
            input: "#baab92",
            ring: "#a37764",
        },
        preview: ["#f1f0e5", "#a37764", "#e4c7b8", "#baab92"],
    },

    mochaMousseDark: {
        name: "Mocha Mousse Dark",
        colors: {
            background: "#2d2521",
            foreground: "#f1f0e5",
            card: "#3c332e",
            "card-foreground": "#f1f0e5",
            popover: "#3c332e",
            "popover-foreground": "#f1f0e5",
            primary: "#c39e88",
            "primary-foreground": "#2d2521",
            secondary: "#8a655a",
            "secondary-foreground": "#f1f0e5",
            muted: "#56453f",
            "muted-foreground": "#c5aa9b",
            accent: "#baab92",
            "accent-foreground": "#2d2521",
            destructive: "#e57373",
            "destructive-foreground": "#2d2521",
            border: "#56453f",
            input: "#56453f",
            ring: "#c39e88",
        },
        preview: ["#2d2521", "#c39e88", "#baab92", "#56453f"],
    },

    modernMinimalLight: {
        name: "Modern Minimal Light",
        colors: {
            background: "#ffffff",
            foreground: "#333333",
            card: "#ffffff",
            "card-foreground": "#333333",
            popover: "#ffffff",
            "popover-foreground": "#333333",
            primary: "#3b82f6",
            "primary-foreground": "#ffffff",
            secondary: "#f3f4f6",
            "secondary-foreground": "#4b5563",
            muted: "#f9fafb",
            "muted-foreground": "#6b7280",
            accent: "#e0f2fe",
            "accent-foreground": "#1e3a8a",
            destructive: "#ef4444",
            "destructive-foreground": "#ffffff",
            border: "#e5e7eb",
            input: "#e5e7eb",
            ring: "#3b82f6",
        },
        preview: ["#ffffff", "#3b82f6", "#e0f2fe", "#e5e7eb"],
    },

    modernMinimalDark: {
        name: "Modern Minimal Dark",
        colors: {
            background: "#171717",
            foreground: "#e5e5e5",
            card: "#262626",
            "card-foreground": "#e5e5e5",
            popover: "#262626",
            "popover-foreground": "#e5e5e5",
            primary: "#3b82f6",
            "primary-foreground": "#ffffff",
            secondary: "#262626",
            "secondary-foreground": "#e5e5e5",
            muted: "#1f1f1f",
            "muted-foreground": "#a3a3a3",
            accent: "#1e3a8a",
            "accent-foreground": "#bfdbfe",
            destructive: "#ef4444",
            "destructive-foreground": "#ffffff",
            border: "#404040",
            input: "#404040",
            ring: "#3b82f6",
        },
        preview: ["#171717", "#3b82f6", "#1e3a8a", "#404040"],
    },

    natureLight: {
        name: "Nature Light",
        colors: {
            background: "#f8f5f0",
            foreground: "#3e2723",
            card: "#f8f5f0",
            "card-foreground": "#3e2723",
            popover: "#f8f5f0",
            "popover-foreground": "#3e2723",
            primary: "#2e7d32",
            "primary-foreground": "#ffffff",
            secondary: "#e8f5e9",
            "secondary-foreground": "#1b5e20",
            muted: "#f0e9e0",
            "muted-foreground": "#6d4c41",
            accent: "#c8e6c9",
            "accent-foreground": "#1b5e20",
            destructive: "#c62828",
            "destructive-foreground": "#ffffff",
            border: "#e0d6c9",
            input: "#e0d6c9",
            ring: "#2e7d32",
        },
        preview: ["#f8f5f0", "#2e7d32", "#c8e6c9", "#e0d6c9"],
    },

    natureDark: {
        name: "Nature Dark",
        colors: {
            background: "#1c2a1f",
            foreground: "#f0ebe5",
            card: "#2d3a2e",
            "card-foreground": "#f0ebe5",
            popover: "#2d3a2e",
            "popover-foreground": "#f0ebe5",
            primary: "#4caf50",
            "primary-foreground": "#0a1f0c",
            secondary: "#3e4a3d",
            "secondary-foreground": "#d7e0d6",
            muted: "#252f26",
            "muted-foreground": "#d7cfc4",
            accent: "#388e3c",
            "accent-foreground": "#f0ebe5",
            destructive: "#c62828",
            "destructive-foreground": "#f0ebe5",
            border: "#3e4a3d",
            input: "#3e4a3d",
            ring: "#4caf50",
        },
        preview: ["#1c2a1f", "#4caf50", "#388e3c", "#3e4a3d"],
    },

    pastelDreamsLight: {
        name: "Pastel Dreams Light",
        colors: {
            background: "#f7f3f9",
            foreground: "#374151",
            card: "#ffffff",
            "card-foreground": "#374151",
            popover: "#ffffff",
            "popover-foreground": "#374151",
            primary: "#a78bfa",
            "primary-foreground": "#ffffff",
            secondary: "#e9d8fd",
            "secondary-foreground": "#4b5563",
            muted: "#f3e8ff",
            "muted-foreground": "#6b7280",
            accent: "#f3e5f5",
            "accent-foreground": "#374151",
            destructive: "#fca5a5",
            "destructive-foreground": "#ffffff",
            border: "#e9d8fd",
            input: "#e9d8fd",
            ring: "#a78bfa",
        },
        preview: ["#f7f3f9", "#a78bfa", "#e9d8fd", "#f3e5f5"],
    },

    pastelDreamsDark: {
        name: "Pastel Dreams Dark",
        colors: {
            background: "#1c1917",
            foreground: "#e0e7ff",
            card: "#2d2535",
            "card-foreground": "#e0e7ff",
            popover: "#2d2535",
            "popover-foreground": "#e0e7ff",
            primary: "#c0aafd",
            "primary-foreground": "#1c1917",
            secondary: "#3f324a",
            "secondary-foreground": "#d1d5db",
            muted: "#20182b",
            "muted-foreground": "#9ca3af",
            accent: "#4a3d5a",
            "accent-foreground": "#d1d5db",
            destructive: "#fca5a5",
            "destructive-foreground": "#1c1917",
            border: "#3f324a",
            input: "#3f324a",
            ring: "#c0aafd",
        },
        preview: ["#1c1917", "#c0aafd", "#3f324a", "#4a3d5a"],
    },

    perpetuityLight: {
        name: "Perpetuity Light",
        colors: {
            background: "#e8f0f0",
            foreground: "#0a4a55",
            card: "#f2f7f7",
            "card-foreground": "#0a4a55",
            popover: "#f2f7f7",
            "popover-foreground": "#0a4a55",
            primary: "#06858e",
            "primary-foreground": "#ffffff",
            secondary: "#d9eaea",
            "secondary-foreground": "#0a4a55",
            muted: "#e0eaea",
            "muted-foreground": "#427a7e",
            accent: "#c9e5e7",
            "accent-foreground": "#0a4a55",
            destructive: "#d13838",
            "destructive-foreground": "#ffffff",
            border: "#cde0e2",
            input: "#d9eaea",
            ring: "#06858e",
        },
        preview: ["#e8f0f0", "#06858e", "#c9e5e7", "#cde0e2"],
    },

    perpetuityDark: {
        name: "Perpetuity Dark",
        colors: {
            background: "#0a1a20",
            foreground: "#4de8e8",
            card: "#0c2025",
            "card-foreground": "#4de8e8",
            popover: "#0c2025",
            "popover-foreground": "#4de8e8",
            primary: "#4de8e8",
            "primary-foreground": "#0a1a20",
            secondary: "#164955",
            "secondary-foreground": "#4de8e8",
            muted: "#0f3039",
            "muted-foreground": "#36a5a5",
            accent: "#164955",
            "accent-foreground": "#4de8e8",
            destructive: "#e83c3c",
            "destructive-foreground": "#f2f2f2",
            border: "#164955",
            input: "#164955",
            ring: "#4de8e8",
        },
        preview: ["#0a1a20", "#4de8e8", "#164955", "#0f3039"],
    },

    quantumRoseLight: {
        name: "Quantum Rose Light",
        colors: {
            background: "#fff0f8",
            foreground: "#91185c",
            card: "#fff7fc",
            "card-foreground": "#91185c",
            popover: "#fff7fc",
            "popover-foreground": "#91185c",
            primary: "#e6067a",
            "primary-foreground": "#ffffff",
            secondary: "#ffd6ff",
            "secondary-foreground": "#91185c",
            muted: "#ffe3f2",
            "muted-foreground": "#c04283",
            accent: "#ffc1e3",
            "accent-foreground": "#91185c",
            destructive: "#d13869",
            "destructive-foreground": "#ffffff",
            border: "#ffc7e6",
            input: "#ffd6ff",
            ring: "#e6067a",
        },
        preview: ["#fff0f8", "#e6067a", "#ffc1e3", "#ffc7e6"],
    },

    quantumRoseDark: {
        name: "Quantum Rose Dark",
        colors: {
            background: "#1a0922",
            foreground: "#ffb3ff",
            card: "#2a1435",
            "card-foreground": "#ffb3ff",
            popover: "#2a1435",
            "popover-foreground": "#ffb3ff",
            primary: "#ff6bef",
            "primary-foreground": "#180518",
            secondary: "#46204f",
            "secondary-foreground": "#ffb3ff",
            muted: "#331941",
            "muted-foreground": "#d67ad6",
            accent: "#5a1f5d",
            "accent-foreground": "#ffb3ff",
            destructive: "#ff2876",
            "destructive-foreground": "#f9f9f9",
            border: "#4a1b5f",
            input: "#46204f",
            ring: "#ff6bef",
        },
        preview: ["#1a0922", "#ff6bef", "#5a1f5d", "#4a1b5f"],
    },

    solarDuskLight: {
        name: "Solar Dusk Light",
        colors: {
            background: "#fdfbf7",
            foreground: "#4a3b33",
            card: "#f8f4ee",
            "card-foreground": "#4a3b33",
            popover: "#f8f4ee",
            "popover-foreground": "#4a3b33",
            primary: "#b45309",
            "primary-foreground": "#ffffff",
            secondary: "#e4c090",
            "secondary-foreground": "#57534e",
            muted: "#f1e9da",
            "muted-foreground": "#78716c",
            accent: "#f2daba",
            "accent-foreground": "#57534e",
            destructive: "#991b1b",
            "destructive-foreground": "#ffffff",
            border: "#e4d9bc",
            input: "#e4d9bc",
            ring: "#b45309",
        },
        preview: ["#fdfbf7", "#b45309", "#f2daba", "#e4d9bc"],
    },

    solarDuskDark: {
        name: "Solar Dusk Dark",
        colors: {
            background: "#1c1917",
            foreground: "#f5f5f4",
            card: "#292524",
            "card-foreground": "#f5f5f4",
            popover: "#292524",
            "popover-foreground": "#f5f5f4",
            primary: "#f97316",
            "primary-foreground": "#ffffff",
            secondary: "#57534e",
            "secondary-foreground": "#e7e5e4",
            muted: "#201d1a",
            "muted-foreground": "#a8a29e",
            accent: "#1e4252",
            "accent-foreground": "#e7e5e4",
            destructive: "#dc2626",
            "destructive-foreground": "#ffffff",
            border: "#44403c",
            input: "#44403c",
            ring: "#f97316",
        },
        preview: ["#1c1917", "#f97316", "#1e4252", "#44403c"],
    },

    starryNightLight: {
        name: "Starry Night Light",
        colors: {
            background: "#f5f7fa",
            foreground: "#1a2238",
            card: "#e3eaf2",
            "card-foreground": "#1a2238",
            popover: "#fffbe6",
            "popover-foreground": "#1a2238",
            primary: "#3a5ba0",
            "primary-foreground": "#fffbe6",
            secondary: "#f7c873",
            "secondary-foreground": "#1a2238",
            muted: "#e5e5df",
            "muted-foreground": "#3a5ba0",
            accent: "#6ea3c1",
            "accent-foreground": "#fffbe6",
            destructive: "#2d1e2f",
            "destructive-foreground": "#fffbe6",
            border: "#b0b8c1",
            input: "#6ea3c1",
            ring: "#f7c873",
        },
        preview: ["#f5f7fa", "#3a5ba0", "#f7c873", "#6ea3c1"],
    },

    starryNightDark: {
        name: "Starry Night Dark",
        colors: {
            background: "#181a24",
            foreground: "#e6eaf3",
            card: "#23243a",
            "card-foreground": "#e6eaf3",
            popover: "#23243a",
            "popover-foreground": "#ffe066",
            primary: "#3a5ba0",
            "primary-foreground": "#ffe066",
            secondary: "#ffe066",
            "secondary-foreground": "#23243a",
            muted: "#1d1e2f",
            "muted-foreground": "#7a88a1",
            accent: "#bccdf0",
            "accent-foreground": "#181a24",
            destructive: "#a04a6c",
            "destructive-foreground": "#ffe066",
            border: "#2d2e3e",
            input: "#3a5ba0",
            ring: "#ffe066",
        },
        preview: ["#181a24", "#3a5ba0", "#ffe066", "#bccdf0"],
    },

    sunsetHorizonLight: {
        name: "Sunset Horizon Light",
        colors: {
            background: "#fff9f5",
            foreground: "#3d3436",
            card: "#ffffff",
            "card-foreground": "#3d3436",
            popover: "#ffffff",
            "popover-foreground": "#3d3436",
            primary: "#ff7e5f",
            "primary-foreground": "#ffffff",
            secondary: "#ffedea",
            "secondary-foreground": "#b35340",
            muted: "#fff0eb",
            "muted-foreground": "#78716c",
            accent: "#feb47b",
            "accent-foreground": "#3d3436",
            destructive: "#e63946",
            "destructive-foreground": "#ffffff",
            border: "#ffe0d6",
            input: "#ffe0d6",
            ring: "#ff7e5f",
        },
        preview: ["#fff9f5", "#ff7e5f", "#feb47b", "#ffe0d6"],
    },

    sunsetHorizonDark: {
        name: "Sunset Horizon Dark",
        colors: {
            background: "#2a2024",
            foreground: "#f2e9e4",
            card: "#392f35",
            "card-foreground": "#f2e9e4",
            popover: "#392f35",
            "popover-foreground": "#f2e9e4",
            primary: "#ff7e5f",
            "primary-foreground": "#ffffff",
            secondary: "#463a41",
            "secondary-foreground": "#f2e9e4",
            muted: "#30272c",
            "muted-foreground": "#d7c6bc",
            accent: "#feb47b",
            "accent-foreground": "#2a2024",
            destructive: "#e63946",
            "destructive-foreground": "#ffffff",
            border: "#463a41",
            input: "#463a41",
            ring: "#ff7e5f",
        },
        preview: ["#2a2024", "#ff7e5f", "#feb47b", "#463a41"],
    },

    t3ChatLight: {
        name: "T3 Chat Light",
        colors: {
            background: "#faf5fa",
            foreground: "#501854",
            card: "#faf5fa",
            "card-foreground": "#501854",
            popover: "#ffffff",
            "popover-foreground": "#501854",
            primary: "#a84370",
            "primary-foreground": "#ffffff",
            secondary: "#f1c4e6",
            "secondary-foreground": "#77347c",
            muted: "#f6e5f3",
            "muted-foreground": "#834588",
            accent: "#f1c4e6",
            "accent-foreground": "#77347c",
            destructive: "#ab4347",
            "destructive-foreground": "#ffffff",
            border: "#efbdeb",
            input: "#e7c1dc",
            ring: "#db2777",
        },
        preview: ["#faf5fa", "#a84370", "#f1c4e6", "#efbdeb"],
    },

    t3ChatDark: {
        name: "T3 Chat Dark",
        colors: {
            background: "#221d27",
            foreground: "#d2c4de",
            card: "#2c2632",
            "card-foreground": "#dbc5d2",
            popover: "#100a0e",
            "popover-foreground": "#f8f1f5",
            primary: "#a3004c",
            "primary-foreground": "#efc0d8",
            secondary: "#362d3d",
            "secondary-foreground": "#d4c7e1",
            muted: "#28222d",
            "muted-foreground": "#c2b6cf",
            accent: "#463753",
            "accent-foreground": "#f8f1f5",
            destructive: "#301015",
            "destructive-foreground": "#ffffff",
            border: "#3b3237",
            input: "#3e343c",
            ring: "#db2777",
        },
        preview: ["#221d27", "#a3004c", "#463753", "#3b3237"],
    },

    // Add more themes here as you provide them
};

export const getTheme = (themeName) => {
    return themes[themeName] || themes.default;
};

export const applyTheme = (themeName) => {
    const theme = getTheme(themeName);
    const root = document.documentElement;

    Object.entries(theme.colors).forEach(([key, value]) => {
        root.style.setProperty(`--${key}`, value);
    });

    // Save to localStorage
    if (typeof window !== "undefined") {
        localStorage.setItem("jammify-theme", themeName);
    }
};

export const getSavedTheme = () => {
    if (typeof window !== "undefined") {
        return localStorage.getItem("jammify-theme") || "default";
    }
    return "default";
};
